spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_api
    username: root
    password: P@ssWord

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: auto
